### ISSUE TITLE
'user_authentication' is undefined

### ISSUE THREAD

**Issue by anplath** [deepshore/chirpstack-operator#28]
**Describe the bug**
The pod operator manager failed to complete starting.
It loops and ends with an error:

TASK [Manage configuration (Chirpstack)] ********************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'user_authentication' is undefined"}

**To Reproduce**
1. Upgrade to v0.0.7

**Expected behavior**
the pod should complete the start without any errors

**Screenshots**
![grafik](https://github.com/user-attachments/assets/69b047c5-5819-4cd5-a59a-52bb98a8ced0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by grothesk** [comment]
Fixed this by fixing the build pipeline.
